#!/usr/bin/env python3
import argparse
import json
import math
import pathlib
import struct


SUPPORTED = {
    ("fwht", "warp-register", "fp32"): set(range(3, 16)),
    ("fft", "thread-dft8", "fp32"): {3},
    ("fft", "cta-dft8", "fp32"): set(range(3, 11)),
    ("fft", "wmma-dft8", "fp16-fp32"): {3},
}


def load_points(path, operators, cores, log_ns):
    document = json.loads(path.read_text())
    points = {}
    cta_threads = set()
    for entry in document.get("design_points", []):
        key = (entry["operator"], entry["core"], entry["precision"])
        if key not in SUPPORTED:
            raise ValueError(f"unsupported generated design family: {key}")
        selected = set(entry["log_n"])
        invalid = selected - SUPPORTED[key]
        if invalid:
            raise ValueError(f"unsupported logN values for {key}: {sorted(invalid)}")
        if operators and key[0] not in operators:
            selected.clear()
        if cores and key[1] not in cores:
            selected.clear()
        if log_ns:
            selected &= log_ns
        points.setdefault(key, set()).update(selected)
        if key == ("fft", "cta-dft8", "fp32") and selected:
            threads = set(entry.get("tile_threads", [128]))
            invalid_threads = threads - {32, 64, 128, 256}
            if invalid_threads:
                raise ValueError(f"unsupported CTA DFT8 tile_threads: {sorted(invalid_threads)}")
            cta_threads.update(threads)
    return points, cta_threads


def switch_cases(log_ns, call):
    return "\n".join(f"        case {log_n}: {call.format(log_n=log_n)}; return;" for log_n in sorted(log_ns))


def availability(log_ns):
    if not log_ns:
        return "false"
    return " || ".join(f"log_n == {value}" for value in sorted(log_ns))


def write_fwht(path, log_ns):
    cases = switch_cases(log_ns, "launch_register_fwht<{log_n}>(input, output, transforms, batch_distance, element_stride, normalize)")
    thread_cases = "\n".join(
        f"        case {log_n}: return register_fwht_threads({log_n});" for log_n in sorted(log_ns))
    path.write_text(f'''// Generated by scripts/generate_design_points.py. Do not edit.
#include <stdexcept>
#include "generated_unit_api.cuh"
#include "register_fwht.cuh"

namespace cuntt::detail {{
bool generated_register_fwht_available(std::uint32_t log_n) noexcept {{ return {availability(log_ns)}; }}
std::uint32_t generated_register_fwht_threads(std::uint32_t log_n) noexcept {{
    switch (log_n) {{
{thread_cases}
        default: return 0;
    }}
}}
void launch_generated_register_fwht(std::uint32_t log_n, const float* input, float* output, std::uint64_t transforms,
                                    std::uint64_t batch_distance, std::uint64_t element_stride, bool normalize) {{
    switch (log_n) {{
{cases}
        default: throw std::invalid_argument("requested FWHT warp-register design point was not generated");
    }}
}}
}}  // namespace cuntt::detail
''')


def write_thread_fft(path, log_ns):
    cases = switch_cases(log_ns, "launch_thread_fft<{log_n}>(input, output, twiddles, transforms, batch_distance, element_stride, normalize)")
    path.write_text(f'''// Generated by scripts/generate_design_points.py. Do not edit.
#include <stdexcept>
#include "generated_unit_api.cuh"
#include "thread_fft.cuh"

namespace cuntt::detail {{
bool generated_thread_dft8_available(std::uint32_t log_n) noexcept {{ return {availability(log_ns)}; }}
void launch_generated_thread_dft8(std::uint32_t log_n, const Complex32* input, Complex32* output, const Complex32* twiddles,
                                  std::uint64_t transforms, std::uint64_t batch_distance, std::uint64_t element_stride, bool normalize) {{
    switch (log_n) {{
{cases}
        default: throw std::invalid_argument("requested thread DFT8 design point was not generated");
    }}
}}
}}  // namespace cuntt::detail
''')


def write_cta_fft(path, log_ns, tile_threads):
    variants = [(log_n, threads) for log_n in sorted(log_ns) for threads in sorted(tile_threads) if threads * 8 >= 1 << log_n]
    cases = "\n".join(
        f"        case ({log_n}U << 16) | {threads}U: launch_cta_fft<{log_n}, {threads}>(input, output, twiddles, transforms, "
        f"batch_distance, element_stride, normalize); return;"
        for log_n, threads in variants)
    available = " || ".join(f"(log_n == {log_n} && tile_threads == {threads})" for log_n, threads in variants) or "false"
    path.write_text(f'''// Generated by scripts/generate_design_points.py. Do not edit.
#include <stdexcept>
#include "generated_unit_api.cuh"
#include "thread_fft.cuh"

namespace cuntt::detail {{
bool generated_cta_dft8_available(std::uint32_t log_n, std::uint32_t tile_threads) noexcept {{ return {available}; }}
void launch_generated_cta_dft8(std::uint32_t log_n, const Complex32* input, Complex32* output, const Complex32* twiddles,
                               std::uint64_t transforms, std::uint64_t batch_distance, std::uint64_t element_stride,
                               std::uint32_t tile_threads, bool normalize) {{
    switch ((log_n << 16) | tile_threads) {{
{cases}
        default: throw std::invalid_argument("requested CTA DFT8 design point was not generated");
    }}
}}
}}  // namespace cuntt::detail
''')


def half_bits(value):
    return struct.unpack("<H", struct.pack("<e", value))[0]


def dft8_matrix(inverse):
    sign = 1.0 if inverse else -1.0
    matrix = []
    for row in range(16):
        output_imag = row >= 8
        k = row & 7
        for column in range(16):
            input_imag = column >= 8
            n = column & 7
            angle = sign * 2.0 * math.pi * k * n / 8.0
            real = math.cos(angle)
            imag = math.sin(angle)
            if not output_imag and not input_imag:
                value = real
            elif not output_imag and input_imag:
                value = -imag
            elif output_imag and not input_imag:
                value = imag
            else:
                value = real
            if abs(value) < 1.0e-7:
                value = 0.0
            matrix.append(half_bits(value))
    return matrix


def format_u16(values):
    rows = []
    for start in range(0, len(values), 16):
        rows.append("    " + ", ".join(f"0x{value:04x}" for value in values[start:start + 16]))
    return ",\n".join(rows)


def write_wmma_fft(path, log_ns):
    enabled = 3 in log_ns
    launch = "launch_wmma_dft8(input, output, transforms, batch_distance, element_stride, inverse, normalize); return;" if enabled else "break;"
    path.write_text(f'''// Generated by scripts/generate_design_points.py. Do not edit.
#include <stdexcept>
#include "generated_unit_api.cuh"

namespace cuntt::detail {{
__constant__ __align__(32) std::uint16_t generated_dft8_forward[256] = {{
{format_u16(dft8_matrix(False))}
}};
__constant__ __align__(32) std::uint16_t generated_dft8_inverse[256] = {{
{format_u16(dft8_matrix(True))}
}};
}}  // namespace cuntt::detail

#include "wmma_fft.cuh"

namespace cuntt::detail {{
bool generated_wmma_dft8_available(std::uint32_t log_n) noexcept {{ return {availability(log_ns)}; }}
void launch_generated_wmma_dft8(std::uint32_t log_n, const Complex32* input, Complex32* output, std::uint64_t transforms,
                                std::uint64_t batch_distance, std::uint64_t element_stride, bool inverse, bool normalize) {{
    switch (log_n) {{
        case 3: {launch}
        default: throw std::invalid_argument("requested WMMA DFT8 design point was not generated");
    }}
}}
}}  // namespace cuntt::detail
''')


def main():
    parser = argparse.ArgumentParser(description="Generate only selected cuButterfly CUDA design points.")
    parser.add_argument("--spec", required=True, type=pathlib.Path)
    parser.add_argument("--output-dir", required=True, type=pathlib.Path)
    parser.add_argument("--operators", nargs="*", choices=("fwht", "fft"))
    parser.add_argument("--cores", nargs="*", choices=("warp-register", "thread-dft8", "cta-dft8", "wmma-dft8"))
    parser.add_argument("--logNs", nargs="*", type=int)
    args = parser.parse_args()

    points, cta_threads = load_points(args.spec, set(args.operators or ()), set(args.cores or ()), set(args.logNs or ()))
    args.output_dir.mkdir(parents=True, exist_ok=True)
    sources = {
        "generated_register_fwht.cu": (write_fwht, points.get(("fwht", "warp-register", "fp32"), set())),
        "generated_thread_fft.cu": (write_thread_fft, points.get(("fft", "thread-dft8", "fp32"), set())),
        "generated_wmma_fft.cu": (write_wmma_fft, points.get(("fft", "wmma-dft8", "fp16-fp32"), set())),
    }
    for name, (writer, selected) in sources.items():
        writer(args.output_dir / name, selected)
    write_cta_fft(args.output_dir / "generated_cta_fft.cu", points.get(("fft", "cta-dft8", "fp32"), set()), cta_threads)
    source_names = [*sources, "generated_cta_fft.cu"]
    cmake_sources = "\n".join(f'    "${{CMAKE_CURRENT_BINARY_DIR}}/generated/{name}"' for name in source_names)
    (args.output_dir / "design_points.cmake").write_text(f"set(CUNTT_GENERATED_SOURCES\n{cmake_sources}\n)\n")
    (args.output_dir / "design_points.json").write_text(json.dumps({"design_points": [
        {"operator": key[0], "core": key[1], "precision": key[2], "log_n": sorted(values),
         **({"tile_threads": sorted(cta_threads)} if key == ("fft", "cta-dft8", "fp32") else {})}
        for key, values in sorted(points.items()) if values
    ]}, indent=2) + "\n")


if __name__ == "__main__":
    main()
