#!/usr/bin/env python3
import argparse
import json
import pathlib

from fft_design_space import load_space


def load_selection(path, space):
    selection = json.loads(path.read_text())
    if selection.get("schema_version") != 1:
        raise ValueError("unsupported FFT codegen schema")
    target = selection.get("target")
    if target not in space["hardware_profiles"]:
        raise ValueError(f"unknown FFT codegen target: {target}")
    family = selection.get("families", {}).get("cufftdx-online")
    if not family:
        raise ValueError("FFT codegen selection has no cufftdx-online family")
    canonical = next(item for item in space["families"] if item["name"] == "cufftdx-online")
    log_ns = sorted(set(family.get("dimension_log_n", [])))
    pairs = sorted({tuple(pair) for pair in family.get("thread_ept_pairs", [])})
    axis = space["axes"]["dimension"]
    hardware = space["hardware_profiles"][target]
    if not log_ns or not pairs:
        raise ValueError("FFT codegen selection is empty")
    for log_n in log_ns:
        if not canonical["dimension_log_n"]["min"] <= log_n <= canonical["dimension_log_n"]["max"]:
            raise ValueError(f"cuFFTDx online logN={log_n} is outside the canonical family")
    for threads, ept in pairs:
        if threads not in axis["threads"] or ept not in axis["elements_per_thread"]:
            raise ValueError(f"thread/EPT pair is outside the canonical axes: {threads}/{ept}")
        if threads > hardware["max_threads_per_cta"]:
            raise ValueError(f"thread/EPT pair exceeds CTA threads: {threads}/{ept}")
        if threads * ept * 8 > hardware["max_shared_bytes_per_cta"]:
            raise ValueError(f"thread/EPT pair exceeds tiled shared memory: {threads}/{ept}")
    return target, log_ns, pairs


def generate_header(path, target, log_ns, pairs):
    conditions = []
    for log_n in log_ns:
        size = 1 << log_n
        for threads, ept in pairs:
            if ept <= size and threads * ept >= size and (threads * ept) % size == 0:
                conditions.append(f"(log_n == {log_n} && threads == {threads} && ept == {ept})")
    expression = " ||\n           ".join(conditions) or "false"
    path.write_text(f'''// Generated by scripts/generate_fft_codegen.py for {target}. Do not edit.
#pragma once
#include <cstdint>

namespace cuntt::detail {{
inline bool generated_cufftdx_online_available(std::uint32_t log_n, std::uint32_t threads,
                                               std::uint32_t ept) noexcept {{
    return {expression};
}}
}}  // namespace cuntt::detail
''')


def generate_dispatch(path, target, pairs):
    cases = "\n".join(
        f"case ({ept}U << 16) | {threads}U: CUNTT_CUFFTDX_ONLINE_LAUNCH({threads}, {ept}); return;"
        for threads, ept in pairs)
    path.write_text(f'''// Generated by scripts/generate_fft_codegen.py for {target}. Do not edit.
{cases}
''')


def main():
    parser = argparse.ArgumentParser(description="Generate selected cuFFTDx online template dispatch points.")
    parser.add_argument("--space-spec", required=True, type=pathlib.Path)
    parser.add_argument("--selection", required=True, type=pathlib.Path)
    parser.add_argument("--output-dir", required=True, type=pathlib.Path)
    args = parser.parse_args()
    space = load_space(args.space_spec)
    target, log_ns, pairs = load_selection(args.selection, space)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    generate_header(args.output_dir / "generated_cufftdx_online_config.cuh", target, log_ns, pairs)
    generate_dispatch(args.output_dir / "generated_cufftdx_online_dispatch.inc", target, pairs)
    (args.output_dir / "fft_codegen_manifest.json").write_text(json.dumps({
        "schema_version": 1,
        "target": target,
        "family": "cufftdx-online",
        "dimension_log_n": log_ns,
        "thread_ept_pairs": [list(pair) for pair in pairs],
    }, indent=2) + "\n")


if __name__ == "__main__":
    main()
