#!/usr/bin/env python3
import argparse
import csv
import json
import math
import pathlib


INTEGER_FIELDS = ("prefix_log_n", "suffix_log_n", "prefix_threads", "suffix_threads", "prefix_ept", "suffix_ept")
FLOAT_FIELDS = ("median_kernel_ms", "cufft_median_ms", "throughput_vs_cufft")


def select_dispatch(rows):
    winners = [row for row in rows if int(row["rank"]) == 1]
    by_log_n = {}
    for row in winners:
        by_log_n.setdefault(int(row["logN"]), []).append(row)
    entries = []
    for log_n, log_rows in sorted(by_log_n.items()):
        ordered = sorted(log_rows, key=lambda row: int(row["batch"]))
        for index, row in enumerate(ordered):
            if index + 1 == len(ordered):
                max_batch = None
            else:
                left = math.log2(int(row["batch"]))
                right = math.log2(int(ordered[index + 1]["batch"]))
                max_batch = 1 << math.floor((left + right) / 2.0)
            entries.append({
                "logN": log_n, "max_batch": max_batch,
                "candidate_id": row["candidate_id"], "cross_twiddle": row["cross_twiddle"],
                "direct_boundary": row.get("direct_boundary", "direct-strided"),
                **{field: int(row[field]) for field in INTEGER_FIELDS},
                **{field: float(row[field]) for field in FLOAT_FIELDS},
            })
    return entries


def validate_dispatch(document):
    if document.get("schema_version") != 1 or document.get("target") is None:
        raise ValueError("unsupported generated FFT dispatch schema")
    previous = {}
    for entry in document.get("entries", []):
        log_n = int(entry["logN"])
        maximum = entry["max_batch"]
        if maximum is not None and int(maximum) < 1:
            raise ValueError("dispatch max_batch must be positive or null")
        if log_n in previous and previous[log_n] is None:
            raise ValueError("unbounded dispatch entry must be last for a length")
        if log_n in previous and maximum is not None and int(maximum) <= int(previous[log_n]):
            raise ValueError("dispatch thresholds must increase")
        previous[log_n] = maximum
    if not document.get("entries"):
        raise ValueError("generated FFT dispatch is empty")


def generate_header(path, document):
    validate_dispatch(document)
    conditions = []
    for entry in document["entries"]:
        threshold = "true" if entry["max_batch"] is None else f"batch <= {int(entry['max_batch'])}ULL"
        recurrence = "true" if entry["cross_twiddle"] == "recurrence" else "false"
        tiled_transpose = "true" if entry.get("direct_boundary") == "tiled-transpose" else "false"
        conditions.append(
            f"    if (log_n == {int(entry['logN'])}U && {threshold}) {{\n"
            f"        mapping = {{{int(entry['prefix_log_n'])}U, {int(entry['prefix_threads'])}U, "
            f"{int(entry['suffix_threads'])}U, {int(entry['prefix_ept'])}U, "
            f"{int(entry['suffix_ept'])}U, {recurrence}, {tiled_transpose}}};\n"
            f"        return true;\n    }}")
    body = "\n".join(conditions)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f'''// Generated by scripts/generate_fft_dispatch.py for {document["target"]}. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace cuntt::detail {{
struct GeneratedFftMapping {{
    std::uint32_t local_stages;
    std::uint32_t prefix_threads;
    std::uint32_t suffix_threads;
    std::uint32_t prefix_ept;
    std::uint32_t suffix_ept;
    bool recurrence_twiddle;
    bool tiled_transpose;
}};

inline bool select_generated_fft_mapping(std::uint32_t log_n, std::size_t batch,
                                         GeneratedFftMapping& mapping) noexcept {{
{body}
    return false;
}}
}}  // namespace cuntt::detail
''')


def main():
    parser = argparse.ArgumentParser(description="Generate measured FFT dispatch data or its C++ header.")
    parser.add_argument("--summary", type=pathlib.Path)
    parser.add_argument("--target", default="v100-sm70")
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--dispatch", type=pathlib.Path)
    parser.add_argument("--header", type=pathlib.Path)
    args = parser.parse_args()
    if args.summary:
        if args.output is None:
            raise ValueError("--summary requires --output")
        with args.summary.open() as source:
            rows = list(csv.DictReader(source))
        document = {"schema_version": 1, "target": args.target, "entries": select_dispatch(rows)}
        validate_dispatch(document)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(document, indent=2) + "\n")
        return
    if args.dispatch and args.header:
        generate_header(args.header, json.loads(args.dispatch.read_text()))
        return
    raise ValueError("use --summary/--output or --dispatch/--header")


if __name__ == "__main__":
    main()
